version: "3"
services:
  mysql:
    image: mysql
    container_name: "container_mysql"
    command: --default-authetication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - networkbridge

  nginx:
    image: nginx
    container_name: "container_nginx"
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment: 
      NGINX_PORT: 80
    networks:
      - networkbridge

networks:
  networkbridge:
    driver: bridge